[project]
name = "era5dp"
version = "1.1"
description = "A pipeline to transform data into AmeriFlux predictors."
readme = "README.md"
dependencies = [
    "cdsapi",
    "xarray",
    "numpy",
    "pandas",
    "numexpr",
    "ipykernel",
    "netCDF4",
    "beautifulsoup4",
    "pyyaml",
    "rioxarray",
    "dask",
    "flask",
    "flask-wtf",
    "pexpect"
]

[project.scripts]
era5dp = "era5dp.main:run"

[tool.setuptools]
packages = ["era5dp"]
