[project]
name = "carbonpipeline"
version = "1.0.2"
description = "A pipeline to transform data into AmeriFlux predictors."
readme = "README.md"
dependencies = [
    "cdsapi",
    "xarray",
    "numpy",
    "pandas",
    "numexpr",
    "ipykernel",
    "netCDF4",
    "beautifulsoup4",
    "pyyaml",
    "rioxarray",
    "dask",
    "flask",
    "flask-wtf",
    "pexpect"
]

[project.scripts]
carbonpipeline = "carbonpipeline.main:run"

[tool.setuptools]
packages = ["carbonpipeline"]
