action: download
data-file: "examples/site/data.csv"
location-coordinates: [48.2167, -82.1556] # inside site/meta.json
start-date: "2014-12-01 00:00:00"
end-date: "2014-12-31 23:00:00"
ameriflux-predictors: [TA, PA, P, WS, WD, VPD, RH, CO2]
manifest: "manifests/example_run.json"