action: download
geometries-directory: "examples/geojsons"
start-date: "2015-12-01 00:00:00"
end-date: "2015-12-31 23:00:00"
ameriflux-predictors: [TA, PA, P, WS, WD, VPD, RH] 
aggregation-type: MONTHLY
id-field: GID
manifest: "manifests/example_run.json"
